global:
 scrape_interval: 10s
scrape_configs:
 - job_name: 'prometheus_metrics'
   scrape_interval: 5s
   static_configs:
     - targets: ['103.187.147.66:9090']
 - job_name: 'node_exporter_metrics'
   scrape_interval: 5s
   static_configs:  
     - targets: ['103.187.147.66:9100','103.189.235.121:9100','103.189.235.96:9100']
 - job_name: 'cadvisor'
   scrape_interval: 5s
   static_configs:
     - targets: ['103.187.147.66:8080','103.189.235.121:8080','103.189.235.96:8080']
